Update sailtrack-ground fork to reflect changes in sailtrack-core v1.3.0
metis-vela-unipd/sailtrack-ground pull request #14
Opened 2024-03-24 16:48 UTC by Magform

2024-03-25 22:23 UTC, matteocarnelos requested changes
Well done! However, you left some "Core" references somewhere. I should have highlighted all of them, but consider doing a global search with your IDE to find all the left occurrences,  if any.

2024-03-25 22:23 UTC, matteocarnelos commented on .build/sailtrack-build
> +sailtrack_image_name="SailTrack-Core_RPi-ARMv8-$debian_release_name"
```suggestion
sailtrack_image_name="SailTrack-Ground_RPi-ARMv8-$debian_release_name"
```

2024-03-25 22:23 UTC, matteocarnelos commented on .github/workflows/build.yml
> +          path: SailTrack-Core_RPi-ARMv8-Bookworm.7z
```suggestion
          name: SailTrack-Ground_RPi-ARMv8-Bookworm.7z
          path: SailTrack-Ground_RPi-ARMv8-Bookworm.7z
```

2024-03-25 22:23 UTC, matteocarnelos commented on .github/workflows/publish.yml
> +          files: SailTrack-Core_RPi-ARMv8-Bookworm.7z
```suggestion
          files: SailTrack-Ground_RPi-ARMv8-Bookworm.7z
```

2024-03-27 10:23 UTC, Magform commented
I should have removed all "Core" references

2024-03-27 22:23 UTC, matteocarnelos approved these changes
LGTM

2024-03-28 10:06 UTC, merged